config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :content, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :category_id, presence: true

  default_scope -> { includes(:user).order(created_at: :desc) }

  scope :by_category, -> (branch, category_name) do
    joins(:category).where(categories: {name: category_name, branch: branch})
  end

  scope :by_branch, -> (branch) do
    joins(:category).where(categories: {branch: branch})
  end

  scope :search, -> (search) do
    where("title ILIKE lower(?) OR content ILIKE lower(?)", "%#{search}%", "%#{search}%")
  end
end

app/models/private/conversation.rb
class Private::Conversation < ApplicationRecord
  self.table_name = 'private_conversations'

  has_many :messages,
           class_name: "Private::Message",
           foreign_key: :conversation_id
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
end

app/models/private/message.rb
class Private::Message < ApplicationRecord
  self.table_name = 'private_messages'

  belongs_to :user
  belongs_to :conversation,
             class_name: 'Private::Conversation',
             foreign_key: :conversation_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # when a user gets deleted, all posts what the user has created will be deleted too.
  has_many :posts, dependent: :destroy

  has_many :private_messages, class_name: 'Private::Message'
  has_many  :private_conversations,
            foreign_key: :sender_id,
            class_name: 'Private::Conversation'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def redirect_if_not_signed_in
    redirect_to root_path if !user_signed_in?
  end

  def redirect_if_signed_in
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @hobby_posts = Post.by_branch('hobby').limit(8)
    @study_posts = Post.by_branch('study').limit(8)
    @team_posts = Post.by_branch('team').limit(8)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_if_not_signed_in, only: [:new]

  def show
    @post = Post.find(params[:id])
  end

  def hobby
    posts_for_branch(params[:action])
  end

  def study
    posts_for_branch(params[:action])
  end

  def team
    posts_for_branch(params[:action])
  end

  def new
    @branch = params[:branch]
    @categories = Category.where(branch: @branch)
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      redirect_to root_path
    end
  end


  private

  def posts_for_branch(branch)
    @categories = Category.where(branch: branch)
    @posts = get_posts.paginate(page: params[:page])
  end

  def get_posts
    PostsForBranchService.new({
                                  search: params[:search],
                                  category: params[:category],
                                  branch: params[:action]
                              }).call
  end

  def post_params
    params.require(:post).permit(:content, :title, :category_id)
        .merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
# give access to the navigation_helper file content
require 'navigation_helper.rb'

module ApplicationHelper
  # inject this module into application_helper
  include NavigationHelper
  include PostsHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def create_new_post_partial_path
    if user_signed_in?
      'posts/partials/create_new_post/signed_in'
    else
      'posts/partials/create_new_post/not_signed_in'
    end
  end

  def all_categories_button_partial_path
    if params[:category].blank?
      'posts/partials/categories/all_selected'
    else
      'posts/partials/categories/all_not_selected'
    end
  end

  def no_posts_partial_path(posts)
    posts.empty? ? 'posts/partials/no_posts' : 'shared/empty_partial'
  end

  def post_format_partial_path
    current_page?(root_path) ? 'posts/post/home_page' : 'posts/post/branch_page'
  end

  def category_field_partial_path
    if params[:category].present?
      'posts/branch/search_form/category_field'
    else
      'shared/empty_partial'
    end
  end
end

app/views/layouts/_navigation.html.erb
<div class="container">
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">

      <div class="row">

        <!-- Elements visible all the time -->
        <div class="col-sm-6">
          <%= render 'layouts/navigation/header' %>
        </div><!-- col-sm-7 -->

        <!-- Elements collapses on smaller devices -->
        <div class="col-sm-6">
          <%= render 'layouts/navigation/collapsible_elements' %>
        </div><!-- col-sm-5 -->

      </div><!-- row -->
  </nav>
</div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collabfield</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="navbar-collapsible-content">
  <ul class="navbar-nav ml-auto">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-brand mb-0 h1">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to 'COLLABFIELD', root_path, class: 'navbar-brand' %>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<ul class="navbar-nav ml-auto">
  <li class="nav-item"> <%= link_to 'Login', login_path, class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link'%></li>
</ul>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<div class="dropdown ml-auto pc-menu">
  <a id="user-settings" class="dropdown-toggle dropdown-header" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <div class="dropdown-menu" role="menu">
    <a><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></a>
    <a><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></a>
  </div>
</div>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>

app/views/pages/partials/side_menu/_no_login_required_links.html.erb
<li id="hobby">
  <%= link_to hobby_posts_path do %>
    <i class="fa fa-user-circle-o" aria-hidden="true"></i> Find a hobby buddy
  <% end %>
</li>

<li id="study">
  <%= link_to study_posts_path do %>
    <i class="fa fa-graduation-cap" aria-hidden="true"></i> Find a study buddy
  <% end %>
</li>

<li id="team">
  <%= link_to team_posts_path do %>
    <i class="fa fa-users" aria-hidden="true"></i> Find a team member
  <% end %>
</li>

app/views/posts/_branch.html.erb
<div id="branch-main-content" class="container">
  <div class="row">
    <h1 class="page-title"><%= page_title %></h1>
    <%= render 'posts/partials/create_new_post', branch: branch %>
  </div><!-- row -->

  <div class="row">
    <%= render  'posts/partials/search_form',
                branch: branch,
                search_placeholder: search_placeholder %>
  </div><!-- row -->

  <div class="row">
    <%= render 'posts/partials/categories', branch: branch %>
  </div>

  <div class="row">
    <div class="col-sm-12" id="feed">
      <%= render @posts %>
      <%= render no_posts_partial_path(@posts) %>
    </div>
  </div><!-- row -->

  <div class="infinite-scroll">
    <%= will_paginate @posts %>
  </div>
</div><!-- container -->

app/views/posts/_modal.html.erb
<!-- Modal -->
<div  class="modal myModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="loaded-data">
          <h3></h3>
          <p></p>
          <div class="interested"><a href="">I'm interested</a></div>
        </div><!-- loaded-data -->
      </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<%= render post_format_partial_path, post: post %>

app/views/posts/hobby.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
    branch: 'hobby',
    page_title: 'Find a person with the same hobby',
    search_placeholder: 'E.g. guitar playing, programming, cooking'
} %>

app/views/posts/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a new post</h1>
      <%= render 'posts/new/post_form' %>
    </div>
  </div>
</div>

app/views/posts/partials/_categories.html.erb
<% branch_path_name = "#{params[:action]}_posts_path" %>

<div class="col-sm-12">
  <ul class="categories-list">
    <%= render all_categories_button_partial_path,
               branch_path_name: branch_path_name %>
    <% @categories.each do |category| %>
      <li class="category-item">
        <%= link_to category.name,
                    send(branch_path_name, category: category.name),
                    :class => ("selected-item" if params[:category] == category.name) %>
      </li>
    <% end %>
  </ul>
</div><!-- col-sm-12 -->

app/views/posts/partials/_create_new_post.html.erb
<div class="col-sm-12">
  <div class="col-sm-8 col-sm-offset-2">
    <%= render create_new_post_partial_path, branch: branch %>
  </div><!-- col-sm-8 -->
</div><!-- col-sm-12 -->

app/views/posts/partials/_no_posts.html.erb
<div class="text-center">Currently there are no published posts</div>

app/views/posts/partials/_search_form.html.erb
<div class="col-sm-12">
  <%= form_tag(send("#{branch}_posts_path"),
               :method => "get",
               id: "search-form") do %>
    <i class="fa fa-search" aria-hidden="true"></i>
    <%= text_field_tag  :search,
                        params[:search],
                        placeholder: search_placeholder,
                        class: "form-control" %>
    <%= render category_field_partial_path %>
  <% end %>
</div><!-- col-sm-12 -->

app/views/posts/partials/categories/_all_not_selecgted.html.erb
<li class="category-item">
  <%= link_to "All", send(branch_path_name) %>
</li>

app/views/posts/partials/categories/_all_selected.html.erb
<li class="category-item">
  <%= link_to "All",
              send(branch_path_name),
              :class => "selected-item"  %>
</li>

app/views/posts/partials/create_new_post/_not_signed_in.html.erb
<div class="text-center login-branch">
  To create a new post you have to
  <%= link_to 'Login',
              login_path,
              class: 'login-button login-button-branch' %>
</div>

app/views/posts/partials/create_new_post/_signed_in.html.erb
<div class="new-post-button-parent">
  <span>Cannot find anyone? Try to: </span>
  <%= link_to "Create a new post",
              new_post_path(branch: branch),
              :class => "new-post-button" %>
</div>

app/views/posts/partials/search_form/_category_field.html.erb
<%= hidden_field_tag :category, params[:category] %>

app/views/posts/post/_branch_page.html.erb
<div class="single-post-list" id=<%= post_path(post.id) %>>
  <%= truncate(post.title, :length => 60) %>
  <div class="post-content">
    <div class="posted-by">Posted by <%= post.user.name %></div>
    <h3><%= post.title %></h3>
    <p><%= post.content %></p>
    <%= link_to "I'm interested", post_path(post.id), class: 'interested' %>
  </div>
</div>

app/views/posts/post/_home_page.html.erb
  <div class="col single-post-card" id=<%= post_path(post.id) %>>
    <div class="card text-center">
      <div class="card-block">
        <h4 class="post-text card-header">
          <div class="posted-by">Posted by <%= post.user.name %></div>
        </h4>
        <div class="post-content">
          <div><%= truncate(post.title, :length => 60) %></div>
          <h3><%= post.title %></h3>
          <p><%= post.content %></p>
          <%= link_to "I'm interested", post_path(post.id), class: 'interested' %>
        </div>
      </div>
    </div><!-- card -->
  </div><!-- col-sm-3 -->

app/views/posts/show.html.erb
<div id="single-post-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @post.user.name %></div>
      <h3><%= @post.title %></h3>
      <p><%= @post.content %></p>
    </div>
  </div><!-- row -->
</div>

app/views/posts/study.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
    branch: 'study',
    page_title: 'Find a person who studies the same field as you',
    search_placeholder: 'E.g. nutrition, calculus, astrophysics'
} %>

app/views/posts/team.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
    branch: 'team',
    page_title: 'Find a person with similar interests as yours to your team',
    search_placeholder: 'E.g. musician for a band, developer for a project'
} %>